export const illustrations = {
  loading: require('../assets/mobile-ui/loading.jpg'),
  login: require('../assets/mobile-ui/login.jpg'),
  recover: require('../assets/mobile-ui/recover-password.jpg'),
  studentVerification: require('../assets/mobile-ui/student-verification.jpg'),
  validId: require('../assets/mobile-ui/valid-id.jpg'),
  wallet: require('../assets/mobile-ui/wallet.jpg'),
  credentialDetails: require('../assets/mobile-ui/credential-details.jpg'),
  credentialShare: require('../assets/mobile-ui/credential-share.jpg'),
  credentialVerified: require('../assets/mobile-ui/credential-verified.jpg'),
  emptyCredentials: require('../assets/mobile-ui/empty-credentials.jpg'),
  emptyNotifications: require('../assets/mobile-ui/empty-notifications.jpg'),
  emptyActivity: require('../assets/mobile-ui/empty-activity.jpg'),
  loadingCredentials: require('../assets/mobile-ui/loading-credentials.jpg'),
  scanQr: require('../assets/mobile-ui/scan-qr.jpg'),
  cameraPermission: require('../assets/mobile-ui/camera-permission.jpg'),
  notificationPermission: require('../assets/mobile-ui/notification-permission.jpg'),
  security: require('../assets/mobile-ui/security.jpg'),
  privacy: require('../assets/mobile-ui/privacy.jpg'),
  biometric: require('../assets/mobile-ui/biometric.jpg'),
  about: require('../assets/mobile-ui/about.jpg'),
  support: require('../assets/mobile-ui/support.jpg'),
  maintenance: require('../assets/mobile-ui/maintenance.jpg'),
  networkError: require('../assets/mobile-ui/network-error.jpg'),
  success: require('../assets/mobile-ui/success.jpg'),
  error: require('../assets/mobile-ui/error.jpg')
};
